[package]
name = "icrp107_data"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bitflags = "1"
fixed_width = "0.4"
fixed_width_derive = "0.4"
once_cell = "1.9.0"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_plain = "1"
thiserror = "1"
uom = { version = "0.32.0" }

